// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char IP[]      = SECRET_OPTIONAL_IP;
const char DNS[]     = SECRET_OPTIONAL_DNS;
const char GATEWAY[] = SECRET_OPTIONAL_GATEWAY;
const char NETMASK[] = SECRET_OPTIONAL_NETMASK;

void onIniciadoChange();
void onBtn1Change();

float iniciado;
CloudLight btn1;

void initProperties(){

  ArduinoCloud.addProperty(iniciado, READWRITE, ON_CHANGE, onIniciadoChange);
  ArduinoCloud.addProperty(btn1, READWRITE, ON_CHANGE, onBtn1Change);

}

EthernetConnectionHandler ArduinoIoTPreferredConnection(IP, DNS, GATEWAY, NETMASK);